# Generated by Django 2.1.7 on 2019-05-02 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=35)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=400)),
                ('start_date', models.DateField(verbose_name='date started')),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Programs')),
            ],
        ),
    ]
