# Generated by Django 2.1.7 on 2019-04-17 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0002_auto_20190416_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='project_members',
        ),
        migrations.AddField(
            model_name='programs',
            name='project_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
