# Generated by Django 2.1.7 on 2019-03-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='belongs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.Programs'),
            preserve_default=False,
        ),
    ]
